//! The wire format exists twice — `sync.rs` and the window's `protocol.ts` —
//! and the two must agree byte for byte.
//!
//! M2.2 built a CI gate for exactly this risk on the schema and left the wire
//! format ungated. This is that gate: Rust writes the fixture, TypeScript
//! asserts against it, and CI fails if the committed file is stale.

use std::path::PathBuf;
use thoughtd::sync::Frame;

fn fixture_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/frames.json")
}

/// Frames chosen to cover what actually varies: every tag, an empty body, a
/// multi-byte document id, and a body containing the length prefix's own bytes.
fn cases() -> Vec<(&'static str, Frame)> {
    vec![
        (
            "subscribe-empty-vector",
            Frame::Subscribe {
                doc_id: "doc-1".into(),
                state_vector: vec![],
            },
        ),
        (
            "subscribe-with-vector",
            Frame::Subscribe {
                doc_id: "doc-1".into(),
                state_vector: vec![0, 1, 2, 255],
            },
        ),
        (
            "sync",
            Frame::Sync {
                doc_id: "doc-1".into(),
                update: vec![1, 0, 0, 0, 5],
            },
        ),
        (
            "update",
            Frame::Update {
                doc_id: "01a02d26-ac02-7072".into(),
                update: vec![42; 8],
            },
        ),
        (
            "broadcast",
            Frame::Broadcast {
                doc_id: "doc-2".into(),
                update: vec![7, 7, 7],
            },
        ),
        (
            "awareness",
            Frame::Awareness {
                doc_id: "doc-2".into(),
                payload: b"cursor".to_vec(),
            },
        ),
        (
            "error",
            Frame::Error {
                doc_id: "doc-3".into(),
                message: "no such document".into(),
            },
        ),
        (
            "presence",
            Frame::Presence {
                doc_id: "doc-2".into(),
                actor: r#"{"actor_id":"agent:opus","name":"opus"}"#.into(),
            },
        ),
        (
            "ack",
            Frame::Ack {
                doc_id: "doc-2".into(),
            },
        ),
        (
            // A non-ASCII id: the length prefix counts bytes, not characters,
            // and a decoder that slices by character position breaks here.
            "unicode-doc-id",
            Frame::Sync {
                doc_id: "документ".into(),
                update: vec![9],
            },
        ),
    ]
}

fn generate() -> String {
    let entries: Vec<serde_json::Value> = cases()
        .into_iter()
        .map(|(name, frame)| {
            serde_json::json!({
                "name": name,
                "frame": describe(&frame),
                "encoded": frame.encode(),
            })
        })
        .collect();
    serde_json::to_string_pretty(&serde_json::json!({
        "_comment": "Generated by `cargo test -p thoughtd --test wire_fixture`. \
                     The window's protocol.ts asserts against this.",
        "frames": entries,
    }))
    .unwrap()
        + "\n"
}

fn describe(frame: &Frame) -> serde_json::Value {
    let (kind, doc_id, body) = match frame {
        Frame::Subscribe {
            doc_id,
            state_vector,
        } => ("subscribe", doc_id, state_vector.clone()),
        Frame::Sync { doc_id, update } => ("sync", doc_id, update.clone()),
        Frame::Update { doc_id, update } => ("update", doc_id, update.clone()),
        Frame::Broadcast { doc_id, update } => ("broadcast", doc_id, update.clone()),
        Frame::Awareness { doc_id, payload } => ("awareness", doc_id, payload.clone()),
        Frame::Error { doc_id, message } => ("error", doc_id, message.as_bytes().to_vec()),
        Frame::Presence { doc_id, actor } => ("presence", doc_id, actor.as_bytes().to_vec()),
        Frame::Ack { doc_id } => ("ack", doc_id, vec![]),
    };
    serde_json::json!({ "kind": kind, "doc_id": doc_id, "body": body })
}

#[test]
fn fixture_is_current() {
    let generated = generate();
    let path = fixture_path();

    if std::env::var("UPDATE_FIXTURES").is_ok() {
        std::fs::write(&path, &generated).expect("write fixture");
        return;
    }

    let committed = std::fs::read_to_string(&path).unwrap_or_default();
    assert_eq!(
        committed, generated,
        "\nThe wire fixture is stale, so Rust and the window disagree about the \
         protocol.\nRegenerate: UPDATE_FIXTURES=1 cargo test -p thoughtd --test wire_fixture\n"
    );
}

/// Rust must also read back what it writes, or the fixture only proves the
/// encoder is self-consistent.
#[test]
fn every_fixture_frame_decodes_to_itself() {
    for (name, frame) in cases() {
        let decoded =
            Frame::decode(&frame.encode()).unwrap_or_else(|| panic!("`{name}` failed to decode"));
        assert_eq!(
            describe(&decoded),
            describe(&frame),
            "`{name}` changed in transit"
        );
    }
}

/// A truncated or hostile frame must return None, never panic — it arrives on
/// a connection task that would take the endpoint down with it.
#[test]
fn malformed_frames_are_refused_rather_than_panicking() {
    assert!(Frame::decode(&[]).is_none(), "empty");
    assert!(
        Frame::decode(&[0x02, 0, 0]).is_none(),
        "shorter than the header"
    );
    // A length prefix claiming more bytes than the frame contains.
    assert!(
        Frame::decode(&[0x02, 0xff, 0xff, 0xff, 0xff]).is_none(),
        "absurd length"
    );
    assert!(
        Frame::decode(&[0x02, 0, 0, 0, 9, b'a']).is_none(),
        "id longer than body"
    );
    // An unknown tag is not a frame we understand.
    assert!(Frame::decode(&[0x7f, 0, 0, 0, 0]).is_none(), "unknown tag");
}
