/**
 * The wire format lives in two languages. These tests assert the TypeScript
 * half against a fixture generated by the Rust half, so the two cannot drift
 * apart silently — the failure mode being a window that connects, says
 * "connected", and then quietly understands nothing.
 */
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";
import { decode, encode, encodeEditorMutation, Tag } from "./protocol";

type Fixture = {
  frames: {
    name: string;
    frame: { kind: string; doc_id: string; body: number[] };
    encoded: number[];
  }[];
};

const fixture: Fixture = JSON.parse(
  readFileSync(
    resolve(import.meta.dirname, "../../crates/thoughtd/tests/fixtures/frames.json"),
    "utf8",
  ),
);

const TAG_BY_KIND: Record<string, number> = {
  subscribe: Tag.Subscribe,
  sync: Tag.Sync,
  update: Tag.Update,
  broadcast: Tag.Broadcast,
  awareness: Tag.Awareness,
  error: Tag.Error,
  presence: Tag.Presence,
  ack: Tag.Ack,
  editor_mutation: Tag.EditorMutation,
};

describe("editor mutations", () => {
  it("encodes ordered before and after positions ahead of the update", () => {
    const encoded = encodeEditorMutation(
      "doc-1",
      [{ beforeFrom: 2, beforeTo: 5, afterFrom: 2, afterTo: 4 }],
      new Uint8Array([9, 8, 7]),
    );
    const frame = decode(encoded)!;
    expect(frame.tag).toBe(Tag.EditorMutation);
    expect([...frame.body]).toEqual([
      1,
      0, 0, 0, 2,
      0, 0, 0, 5,
      0, 0, 0, 2,
      0, 0, 0, 4,
      9, 8, 7,
    ]);
  });

  it("rejects invalid metadata before allocating a wire frame", () => {
    expect(() =>
      encodeEditorMutation(
        "doc-1",
        [{ beforeFrom: 5, beforeTo: 2, afterFrom: 0, afterTo: 0 }],
        new Uint8Array([1]),
      ),
    ).toThrow(RangeError);
    expect(() => encodeEditorMutation("doc-1", [], new Uint8Array())).toThrow(RangeError);
  });
});

describe("wire format agrees with the daemon", () => {
  it("has frames to check", () => {
    expect(fixture.frames.length).toBeGreaterThan(0);
  });

  for (const entry of fixture.frames) {
    it(`encodes ${entry.name} exactly as Rust does`, () => {
      const encoded = encode(
        TAG_BY_KIND[entry.frame.kind],
        entry.frame.doc_id,
        new Uint8Array(entry.frame.body),
      );
      expect([...encoded]).toEqual(entry.encoded);
    });

    it(`decodes ${entry.name} as Rust encoded it`, () => {
      const frame = decode(new Uint8Array(entry.encoded));
      expect(frame).not.toBeNull();
      expect(frame!.tag).toBe(TAG_BY_KIND[entry.frame.kind]);
      expect(frame!.docId).toBe(entry.frame.doc_id);
      expect([...frame!.body]).toEqual(entry.frame.body);
    });
  }
});

describe("malformed frames", () => {
  it("are refused rather than throwing", () => {
    // These arrive inside a socket handler; a throw there kills the connection.
    expect(decode(new Uint8Array([]))).toBeNull();
    expect(decode(new Uint8Array([Tag.Sync, 0, 0]))).toBeNull();
    expect(decode(new Uint8Array([Tag.Sync, 0xff, 0xff, 0xff, 0xff]))).toBeNull();
    expect(decode(new Uint8Array([Tag.Sync, 0, 0, 0, 9, 97]))).toBeNull();
  });

  it("reads the length prefix from a view, not the whole buffer", () => {
    // A Uint8Array over a larger buffer at a non-zero offset is what a
    // WebSocket message looks like after slicing. Reading the DataView from
    // byte 0 of the underlying buffer instead of the view's offset would
    // decode a different frame entirely.
    const backing = new Uint8Array(64);
    const frame = encode(Tag.Update, "doc-1", new Uint8Array([1, 2, 3]));
    backing.set(frame, 16);
    const view = backing.subarray(16, 16 + frame.length);

    const decoded = decode(view);
    expect(decoded?.docId).toBe("doc-1");
    expect([...(decoded?.body ?? [])]).toEqual([1, 2, 3]);
  });
});
